"""Subclass of MainFrame, which is generated by wxFormBuilder."""

import os
import wx
import wx.dataview
import PureClip

# Implementing MainFrame
class PureClipMainFrame( PureClip.MainFrame ):
	def __init__( self, parent ):
		PureClip.MainFrame.__init__( self, parent )

		self.listCtrl.InsertColumn(0, "序号", width=40)
		self.listCtrl.InsertColumn(1, "文件名", width=280)
		self.listCtrl.InsertColumn(2, "开始时间", width=65)
		self.listCtrl.InsertColumn(3, "结束时间", width=65)
		self.listCtrl.InsertColumn(4, "文件路径", width=238)

	# Handlers for MainFrame events.
	def AddFileBtnOnClick( self, event ):
		# TODO: Implement AddFileBtnOnClick
		self.dirname = ''
		# 文件选择对话框
		FileDlg = wx.FileDialog(self, u"选择导入的文件", self.dirname, "", "*.mp4", wx.FD_OPEN)
		if FileDlg.ShowModal() == wx.ID_OK:
			# 文件导入
			# col 0		id
			# col 1		filename
			# col 2		startTime
			# col 3		endTime
			# col 4		path

			index = self.listCtrl.InsertItem(self.listCtrl.GetItemCount(),self.listCtrl.GetItemCount())
			
			self.listCtrl.SetItem(index, 0, str(index))
			self.listCtrl.SetItem(index, 1, FileDlg.GetFilename())
			self.listCtrl.SetItem(index, 2, "开头")
			self.listCtrl.SetItem(index, 3, "结尾")
			self.listCtrl.SetItem(index, 4, FileDlg.GetPath())

			print(FileDlg.GetFilename(), FileDlg.GetPath())
			
		FileDlg.Destroy()

	def ExportBtnOnClick( self, event ):
		# TODO: Implement ExportBtnOnClick
		pass

	def ProjectWebBtnOnClick( self, event ):
		# TODO: Implement ProjectWebBtnOnClick
		pass
