"""Subclass of MainFrame, which is generated by wxFormBuilder."""

import os
import wx
import PureClip

# Implementing MainFrame
class PureClipMainFrame( PureClip.MainFrame ):
	def __init__( self, parent ):
		PureClip.MainFrame.__init__( self, parent )

	# Handlers for MainFrame events.
	def AddFileBtnOnClick( self, event ):
		# TODO: Implement AddFileBtnOnClick
		self.dirname = ''
		# 文件选择对话框
		FileDlg = wx.FileDialog(self, u"选择导入的文件", self.dirname, "", "*.mp4", wx.FD_OPEN)
		if FileDlg.ShowModal() == wx.OK:
			# 文件导入
			self.filename = FileDlg.GetFilename()
			self.dirname = FileDlg.GetDirectory()
			self.path = os.path.join(self.dirname, self.filename)

		FileDlg.Destroy()

	def ExportBtnOnClick( self, event ):
		# TODO: Implement ExportBtnOnClick
		pass

	def ProjectWebBtnOnClick( self, event ):
		# TODO: Implement ProjectWebBtnOnClick
		pass