"""Subclass of MainFrame, which is generated by wxFormBuilder."""

from export.model import VideoFile
import export
from controller.core import CoreController
import logging
import os
import threading

import wx

import meta
import SimpleCutPy
from message import ExportMessage, WorkStateEnum
from model import VideoSequenceModel


class FileDropTarget(wx.FileDropTarget):
    def __init__(self, target: "SimpleCutPyMainFrame"):
        wx.FileDropTarget.__init__(self)
        self.target = target

    def OnDropFiles(self, x, y, filenames):
        logging.debug(f"FileDropTarget 拖拽文件：{filenames}")
        for file in filenames:
            filepath, filename = os.path.split(file)
            logging.debug(f"解析文件：{file} -> 路径: {filepath}, 文件名: {filename}")
            self.target.core_controller.add_file(filename, filepath)

        self.target.update_video_sequence_view()
        return True


# Implementing MainFrame
class SimpleCutPyMainFrame(SimpleCutPy.MainFrame):
    def __init__(self, parent=None):
        SimpleCutPy.MainFrame.__init__(self, parent)

        # 设置标题
        self.SetTitle(f"Simple Cut Py {meta.VERSION}")

        # 设置拖拽文件
        self.list_ctrl.SetDropTarget(FileDropTarget(self))

        self.first_selected_index = 0
        # self.item_list: list[dict] = []  # 列表是控件上的映射，列表的物品顺序就是控件上物品的顺序
        self.video_sequence: VideoSequenceModel = VideoSequenceModel()

        # list_ctrl 控件添加列
        self.list_ctrl.InsertColumn(0, "序号", width=40)
        self.list_ctrl.InsertColumn(1, "文件名", width=280)
        self.list_ctrl.InsertColumn(2, "开始时间", width=65)
        self.list_ctrl.InsertColumn(3, "结束时间", width=65)
        self.list_ctrl.InsertColumn(4, "文件路径", width=238)

        # 标记版本
        self.VersionText.SetLabelText(f"Simple Cut Py 版本号\n{meta.VERSION}")

        self.core_controller = CoreController(self)

    def _bind_event(self):
        pass

    def on_add_file_button_click(self, event):
        # 文件选择对话框
        file_dlg = wx.FileDialog(self, "选择导入的文件", "", "", "*.mp4", wx.FD_OPEN)
        if file_dlg.ShowModal() == wx.ID_OK:
            # 导入文件
            filepath = file_dlg.GetPath()
            for filename in file_dlg.GetFilenames():
                self.core_controller.add_file(filename, filepath)

                logging.debug("导入文件：{}, {}".format(filename, filepath))

            self.update_video_sequence_view()

        file_dlg.Destroy()

    def on_remove_file_button_click(self, event):
        # 删除列表中的项
        target_idx = self.core_controller.first_select_index

        if target_idx <= -1:
            return  # 如果没有选中

        if target_idx >= self.core_controller.sequence_length():
            return  # 如果超出范围

        self.core_controller.remove_file(target_idx)

        self.update_video_sequence_view()

        # 选中 index
        if target_idx < self.core_controller.sequence_length():
            self.list_ctrl.Select(target_idx)
        elif self.core_controller.sequence_length() > 0:
            self.list_ctrl.Select(self.core_controller.sequence_length() - 1)

    def on_move_up_file_button_click(self, event):
        logging.debug(
            f"on_move_up_file_button_click: {self.core_controller.first_select_index}"
        )

        idx = self.core_controller.first_select_index

        if idx == -1:
            return  # 如果没有选中

        if idx == 0:
            wx.MessageBox(
                "选中素材已置顶。", "错误", style=wx.YES_DEFAULT | wx.ICON_QUESTION
            )
            return  # 如果是第一个物品

        self.core_controller.swap_file(idx, idx - 1)

        self.update_video_sequence_view()

        self.list_ctrl.Select(idx, on=0)  # 取消原来的选中
        self.list_ctrl.Select(idx - 1)

    def on_move_down_file_button_click(self, event):
        logging.debug(
            f"on_move_down_file_button_click: {self.core_controller.first_select_index}"
        )

        idx = self.core_controller.first_select_index

        if idx == -1:
            return  # 如果没有选中

        if idx == self.list_ctrl.GetItemCount() - 1:
            wx.MessageBox(
                "选中素材在最末端。", "错误", style=wx.YES_DEFAULT | wx.ICON_QUESTION
            )
            return  # 如果是最后一个

        self.core_controller.swap_file(idx, idx + 1)

        self.update_video_sequence_view()

        # 选中转移
        self.list_ctrl.Select(idx, on=0)  # 取消原来的选中
        self.list_ctrl.Select(idx + 1)

    def on_export_button_click(self, event):
        # 获取文件名路径
        self.core_controller.task.export_file_name = self.ExportNameCtrl.GetValue()
        self.core_controller.task.export_file_path = self.ExportPathCtrl.GetValue()

        # 读取配置
        self.get_export_config()

        # 导出
        self.core_controller.export_sequence()

        self.ExportBtn.Disable()

        return

    def on_open_project_website_button_click(self, event):
        # TODO: Implement ProjectWebBtnOnClick
        pass

    def on_clear_all_button_click(self, event):
        self.core_controller.clear_all_files()
        logging.debug(f"clear all video: {self.video_sequence.video_list}")
        self.update_video_sequence_view()

    def on_start_time_ctrl_text(self, event):
        """修改开始时间输入框的时候修改itemlist的start_time"""
        index = self.core_controller.first_select_index

        value = self.StartTimeCtrl.GetValue()

        # 尝试更新数据
        try:
            videofile = self.core_controller.get_file(index)
            videofile.start_time = value
        except ValueError as e:
            logging.error(f"Set Start Time Error: {e}")
            return

        self.update_video_file_view(index, videofile)

    def on_end_time_ctrl_text(self, event):
        """修改结束时间输入框的时候修改itemlist的end_time"""
        index = self.core_controller.first_select_index

        value = self.EndTimeCtrl.GetValue()

        # 尝试更新数据
        try:
            videofile = self.core_controller.get_file(index)
            videofile.end_time = value
        except ValueError as e:
            logging.error(f"Set End Time Error: {e}")
            return

        self.update_video_file_view(index, videofile)

    def on_list_item_selected(self, event):
        index = self.list_ctrl.GetFirstSelected()
        self.core_controller.first_select_index = index

        # 获取选中的物品时间，同步到输入框
        self.StartTimeCtrl.SetValue(self.core_controller.get_file(index).start_time)
        self.EndTimeCtrl.SetValue(self.core_controller.get_file(index).end_time)

        logging.debug(
            f"Selected Item Index: {index}, \
                    Selected Item no: {self.core_controller.get_file(index)}"
        )

    def on_export_done(self, msg: ExportMessage):
        logging.debug(f"Export Done: {msg}")
        if msg.state == WorkStateEnum.SUCCESS:
            wx.MessageBox("导出成功", "提示", wx.OK | wx.ICON_INFORMATION)
        elif msg.state == WorkStateEnum.FAIL:
            logging.error(f"Export Error: {msg.message}")
            wx.MessageBox("导出失败", "提示", wx.OK | wx.ICON_INFORMATION)

        if len(self.core_controller.working_thread) == 0:
            self.ExportBtn.Enable()

        return

    def on_size_control_mode_change(self, event):
        size_control_mode = "none"
        match self.SizeControlMode.GetSelection():
            case 0:
                size_control_mode = "x264"
            case 1:
                size_control_mode = "mbps"
            case _:
                size_control_mode = "none"

        # 如果不是 mbps 则隐藏，否则显示
        if size_control_mode == "mbps":
            self.MbpsCtrl.Show()
        else:
            self.MbpsCtrl.Hide()

        return

    def update_video_file_view(self, index: int, file: VideoFile):
        """将 VideoFile 载入到 列表item上

        Args:
            index (int): 列表项索引
            file (VideoFile): 要载入的视频文件
        """
        logging.debug(f"update_video_file_view: {file}, index: {index}")
        # 确保列表控件中有足够的项
        while index >= self.list_ctrl.GetItemCount():
            self.list_ctrl.InsertItem(self.list_ctrl.GetItemCount(), "")

        self.list_ctrl.SetItem(index, 0, str(index + 1))
        self.list_ctrl.SetItem(index, 1, file.file_name)
        self.list_ctrl.SetItem(index, 2, file.start_time)
        self.list_ctrl.SetItem(index, 3, file.end_time)
        self.list_ctrl.SetItem(index, 4, file.file_path)

    def update_video_sequence_view(self, index=-1) -> None:
        """更新视频序列视图

        Args:
            index (int, optional): 要更新的视频序列索引. 默认-1表示更新所有.
        """
        sequence = self.core_controller.task.video_sequence.get_video_list()
        logging.debug(f"update_video_sequence_view: {index}, sequence: {sequence}")
        if index == -1:
            # 清空列表，然后重新添加所有条目，避免空白条目
            self.list_ctrl.DeleteAllItems()
            for i, item in enumerate(sequence):
                # 直接添加到列表末尾
                self.list_ctrl.InsertItem(i, str(i + 1))
                self.list_ctrl.SetItem(i, 1, item.file_name)
                self.list_ctrl.SetItem(i, 2, item.start_time)
                self.list_ctrl.SetItem(i, 3, item.end_time)
                self.list_ctrl.SetItem(i, 4, item.file_path)
            return

        # 只更新单个条目
        if index < len(sequence):
            self.update_video_file_view(index, sequence[index])

    def update_export_config_view(self) -> None:
        """更新导出配置视图"""
        export_config = self.core_controller.task.export_config

        match export_config.size_control:
            case export.model.X264Config():
                self.SizeControlMode.SetSelection(0)
            case export.model.MbpsConfig():
                self.SizeControlMode.SetSelection(1)
                self.MbpsCtrl.SetValue(str(export_config.size_control.mbps))
            case None:
                self.SizeControlMode.SetSelection(2)
            case _:
                self.SizeControlMode.SetSelection(0)

        match export_config.multi_track_mode:
            case "first":
                self.MultiTrackMode.SetSelection(0)
            case "amix":
                self.MultiTrackMode.SetSelection(1)
            case "export_both":
                self.MultiTrackMode.SetSelection(2)
            case _:
                self.MultiTrackMode.SetSelection(0)

    def get_export_config(self) -> None:
        """
        获取导出配置到模型
        """
        size_control_mode = self.size_control_idx_to_enum(
            self.SizeControlMode.GetSelection()
        )

        match size_control_mode:
            case "x264":
                size_control = export.model.X264Config()
            case "mbps":
                size_control = export.model.MbpsConfig(
                    mbps=float(self.MbpsCtrl.GetValue())
                )
            case "none":
                size_control = None
            case _:
                size_control = None

        multi_track_mode = self.multi_track_select_idx_to_enum(
            self.MultiTrackMode.GetSelection()
        )

        export_config = export.model.ExportConfig(
            size_control=size_control,
            multi_track_mode=multi_track_mode,
        )

        self.core_controller.setup_export_config(export_config)

    @staticmethod
    def size_control_idx_to_enum(idx: int):
        """将大小控制模式选择框索引转换为枚举值

        Args:
            idx (int): 大小控制模式选择框索引

        Returns:
            SizeControlMode: 大小控制模式枚举值
        """
        match idx:
            case 0:
                return "x264"
            case 1:
                return "mbps"
            case 2:
                return "none"
            case _:
                return "none"

    @staticmethod
    def multi_track_select_idx_to_enum(idx: int):
        """将多轨道模式选择框索引转换为枚举值

        Args:
            idx (int): 多轨道模式选择框索引

        Returns:
            MultiTrackMode: 多轨道模式枚举值
        """
        match idx:
            case 0:
                return "first"
            case 1:
                return "amix"
            case 2:
                return "export_both"
            case _:
                return "first"


if __name__ == "__main__":
    App = wx.App()
    mainFrame = SimpleCutPyMainFrame(None)
    mainFrame.Show(True)
    App.MainLoop()
